# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  [ repository_dispatch ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
      - run: echo "Triggering test 2"
      
